import { Enemy, Subject, GradeLevel } from '@/types/game';

const BASE_ENEMY_DATABASE: Enemy[] = [
  // === MATEMATIKA ===
  {
    id: 'mat_slime_rumus',
    name: 'Slime Rumus Aljabar',
    title: 'Penjaga Persamaan Linier',
    subject: 'matematika',
    grade: 7,
    level: 1,
    maxHp: 80,
    hp: 80,
    attack: 12,
    defense: 4,
    avatar: '📐',
    elementColor: '#E06C75',
    description: 'Makhluk lendir yang terbentuk dari kumpulan variabel x dan y yang belum terpecahkan.',
    defeatQuote: 'Variabelku akhirnya terdefinisikan...',
    expReward: 45,
    goldReward: 25,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'weapon_wooden_ruler', dropChance: 0.15 },
    ],
  },
  {
    id: 'mat_golem_pythagoras',
    name: 'Golem Pythagoras Segitiga',
    title: 'Penjaga Sisi Miring Hipotenusa',
    subject: 'matematika',
    grade: 8,
    level: 4,
    maxHp: 160,
    hp: 160,
    attack: 24,
    defense: 10,
    avatar: '🔺',
    elementColor: '#E06C75',
    description: 'Monster batu padat yang tersusun dari rumus a² + b² = c².',
    defeatQuote: 'Sudut siku-sikuku runtuh oleh logikamu!',
    expReward: 95,
    goldReward: 55,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'buff_defense', dropChance: 0.3 },
    ],
  },
  {
    id: 'mat_naga_peluang',
    name: 'Naga Statistika & Peluang',
    title: 'Penguasa Distribusi Data',
    subject: 'matematika',
    grade: 9,
    level: 8,
    maxHp: 320,
    hp: 320,
    attack: 42,
    defense: 18,
    avatar: '🐲',
    elementColor: '#E06C75',
    description: 'Naga legendaris yang menyemburkan api probabilitas dan diagram batang raksasa.',
    defeatQuote: 'Peluang kekalahanku ternyata 100% di hadapanmu!',
    expReward: 220,
    goldReward: 130,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.3 },
      { itemId: 'weapon_calculus_staff', dropChance: 0.1 },
    ],
  },

  // === IPA (ILMU PENGETAHUAN ALAM) ===
  {
    id: 'ipa_spora_mikroba',
    name: 'Spora Mikroorganisme Liar',
    title: 'Entitas Sel Uniseluler',
    subject: 'ipa',
    grade: 7,
    level: 1,
    maxHp: 75,
    hp: 75,
    attack: 11,
    defense: 3,
    avatar: '🦠',
    elementColor: '#98C379',
    description: 'Koloni mikroba bersel tunggal yang aktif melakukan pembelahan biner tak terkontrol.',
    defeatQuote: 'Membran selku pecah oleh sainsmu...',
    expReward: 42,
    goldReward: 22,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'buff_attack', dropChance: 0.2 },
    ],
  },
  {
    id: 'ipa_titan_gravitasi',
    name: 'Titan Hukum Newton',
    title: 'Pengendali Gaya Aksi-Reaksi',
    subject: 'ipa',
    grade: 8,
    level: 5,
    maxHp: 190,
    hp: 190,
    attack: 28,
    defense: 12,
    avatar: '🪐',
    elementColor: '#98C379',
    description: 'Raksasa kosmik yang memanfaatkan percepatan gravitasi dan inersia massa.',
    defeatQuote: 'Setiap aksi memang menghasilkan reaksi balik yang setimpal...',
    expReward: 120,
    goldReward: 65,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'scroll_hint', dropChance: 0.35 },
    ],
  },
  {
    id: 'ipa_cyber_atom',
    name: 'Raja Reaktor Listrik Dinamis',
    title: 'Pembangkit Muatan Elektronik',
    subject: 'ipa',
    grade: 9,
    level: 9,
    maxHp: 350,
    hp: 350,
    attack: 45,
    defense: 20,
    avatar: '⚡',
    elementColor: '#98C379',
    description: 'Robot generator bertegangan tinggi yang memancarkan arus searah dan bolak-balik.',
    defeatQuote: 'Arus listrikku telah dinetralkan!',
    expReward: 250,
    goldReward: 150,
    possibleDrops: [
      { itemId: 'potion_hp_large', dropChance: 0.6 },
      { itemId: 'armor_lab_coat', dropChance: 0.2 },
    ],
  },

  // === IPS (ILMU PENGETAHUAN SOSIAL) ===
  {
    id: 'ips_bayangan_arkeolog',
    name: 'Roh Penjelajah Peta Kuno',
    title: 'Penjaga Garis Lintang & Bujur',
    subject: 'ips',
    grade: 7,
    level: 2,
    maxHp: 90,
    hp: 90,
    attack: 14,
    defense: 5,
    avatar: '🧭',
    elementColor: '#D19A66',
    description: 'Roh penjelajah samudra yang tersesat di peta skala besar tanpa kompas yang tepat.',
    defeatQuote: 'Koordinat pemahamanku kini menjadi jelas...',
    expReward: 55,
    goldReward: 30,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.5 },
      { itemId: 'scroll_hint', dropChance: 0.25 },
    ],
  },
  {
    id: 'ips_pendekar_majapahit',
    name: 'Kesatria Benteng Nusantara',
    title: 'Pelindung Jalur Rempah Maritim',
    subject: 'ips',
    grade: 8,
    level: 6,
    maxHp: 220,
    hp: 220,
    attack: 32,
    defense: 15,
    avatar: '🛡️',
    elementColor: '#D19A66',
    description: 'Prajurit pelindung sejarah kerajaan masa lampau yang menguji wawasan kebangsaan.',
    defeatQuote: 'Semangat Sumpah Palapa hidup dalam jiwamu!',
    expReward: 140,
    goldReward: 80,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'armor_school_vest', dropChance: 0.25 },
    ],
  },
  {
    id: 'ips_baron_monopoli',
    name: 'Baron Perdagangan Internasional',
    title: 'Penguasa Valuta Asing & Inflasi',
    subject: 'ips',
    grade: 9,
    level: 8,
    maxHp: 310,
    hp: 310,
    attack: 40,
    defense: 19,
    avatar: '💰',
    elementColor: '#D19A66',
    description: 'Konglomerat bayangan yang memanipulasi hukum permintaan, penawaran, dan pasar global.',
    defeatQuote: 'Kebijakan ekonomimu meruntuhkan monopoliku!',
    expReward: 230,
    goldReward: 180,
    possibleDrops: [
      { itemId: 'talisman_exp', dropChance: 0.4 },
      { itemId: 'potion_hp_large', dropChance: 0.5 },
    ],
  },

  // === BAHASA INDONESIA ===
  {
    id: 'indo_mimik_kata',
    name: 'Mimik Tanda Baca',
    title: 'Pengacau Huruf Kapital & Koma',
    subject: 'indonesia',
    grade: 7,
    level: 2,
    maxHp: 85,
    hp: 85,
    attack: 13,
    defense: 4,
    avatar: '🖋️',
    elementColor: '#61AFEF',
    description: 'Monster lincah yang suka menukar tanda titik koma dan menghilangkan konjungsi penting.',
    defeatQuote: 'Kalimatmu tersusun rapi sesuai EYD...',
    expReward: 50,
    goldReward: 28,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'scroll_hint', dropChance: 0.3 },
    ],
  },
  {
    id: 'indo_penyair_majas',
    name: 'Penyair Majas & Perumpamaan',
    title: 'Penutur Metafora Gelap',
    subject: 'indonesia',
    grade: 8,
    level: 5,
    maxHp: 200,
    hp: 200,
    attack: 30,
    defense: 12,
    avatar: '📜',
    elementColor: '#61AFEF',
    description: 'Penyair misterius yang menyerang dengan larik puisi personifikasi dan hiperbola memukau.',
    defeatQuote: 'Amanat bait puisimu meluluhkan hatiku!',
    expReward: 130,
    goldReward: 70,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'weapon_pen_blade', dropChance: 0.15 },
    ],
  },
  {
    id: 'indo_raja_cerpen',
    name: 'Arsitek Teks Eksplanasi & Pidato',
    title: 'Master Gagasan Pokok & Resensi',
    subject: 'indonesia',
    grade: 9,
    level: 9,
    maxHp: 340,
    hp: 340,
    attack: 44,
    defense: 21,
    avatar: '📖',
    elementColor: '#61AFEF',
    description: 'Penjaga perpustakaan agung yang memegang rahasia struktur teks persuasif dan resensi sastra.',
    defeatQuote: 'Argumenmu tak terbantahkan secara logis!',
    expReward: 240,
    goldReward: 140,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.3 },
      { itemId: 'armor_archmage_robe', dropChance: 0.08 },
    ],
  },

  // === BAHASA INGGRIS ===
  {
    id: 'eng_sprite_grammar',
    name: 'Past Tense Sprite',
    title: 'Irregular Verbs Mischief',
    subject: 'inggris',
    grade: 7,
    level: 2,
    maxHp: 88,
    hp: 88,
    attack: 14,
    defense: 4,
    avatar: '🔤',
    elementColor: '#C678DD',
    description: 'A swift fairy confusing simple present and past tense auxiliary verbs (did, was, were).',
    defeatQuote: 'Your grammar structure is impeccable!',
    expReward: 52,
    goldReward: 26,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'talisman_exp', dropChance: 0.2 },
    ],
  },
  {
    id: 'eng_gargoyle_narrative',
    name: 'Narrative Fable Gargoyle',
    title: 'Keeper of Moral Lessons',
    subject: 'inggris',
    grade: 8,
    level: 6,
    maxHp: 210,
    hp: 210,
    attack: 33,
    defense: 14,
    avatar: '🦇',
    elementColor: '#C678DD',
    description: 'An ancient winged guardian asking deep questions about moral values in classic folklore.',
    defeatQuote: 'You understood the moral lesson completely...',
    expReward: 145,
    goldReward: 75,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'buff_attack', dropChance: 0.3 },
    ],
  },
  {
    id: 'eng_dragon_vocabulary',
    name: 'Vocabulary Sovereign Drake',
    title: 'Master of Idioms & Passive Voice',
    subject: 'inggris',
    grade: 9,
    level: 9,
    maxHp: 360,
    hp: 360,
    attack: 46,
    defense: 22,
    avatar: '🐉',
    elementColor: '#C678DD',
    description: 'A majestic bilingual dragon testing advanced synonym contextual usage and formal letters.',
    defeatQuote: 'Your vocabulary is as vast as the open ocean!',
    expReward: 260,
    goldReward: 160,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.35 },
      { itemId: 'weapon_pen_blade', dropChance: 0.2 },
    ],
  },
];

interface EnemyVariantConfig {
  id: string;
  name: string;
  title: string;
  avatar: string;
  description: string;
  defeatQuote: string;
  maxHp?: number;
  attack?: number;
  defense?: number;
}

/**
 * Tiap kelas punya beberapa penjaga dengan tema yang berbeda. Data dasar lama
 * tetap dipakai, lalu varian ini membuat pilihan musuh tidak selalu sama saat
 * pemain menyelesaikan beberapa gelombang dalam satu sesi.
 */
const ENEMY_VARIANT_CONFIGS: Record<string, EnemyVariantConfig[]> = {
  'mat_slime_rumus': [
    {
      id: 'mat_golem_bilangan',
      name: 'Golem Bilangan Bulat',
      title: 'Penjaga Operasi Hitung',
      avatar: '🔢',
      description: 'Golem batu yang menyusun bilangan positif, negatif, dan pecahan menjadi tantangan baru.',
      defeatQuote: 'Tanda negatifku tak bisa lagi menyembunyikan jawabannya!',
      maxHp: 92,
      attack: 13,
      defense: 5,
    },
    {
      id: 'mat_ranger_perbandingan',
      name: 'Ranger Skala',
      title: 'Pemburu Perbandingan Senilai',
      avatar: '🗺️',
      description: 'Penjelajah kecil yang mengubah jarak di peta menjadi soal perbandingan sehari-hari.',
      defeatQuote: 'Skalaku sudah pas dengan strategimu!',
      maxHp: 104,
      attack: 14,
      defense: 4,
    },
  ],
  'mat_golem_pythagoras': [
    {
      id: 'mat_sphinx_spldv',
      name: 'Sphinx Dua Variabel',
      title: 'Penjaga x dan y',
      avatar: '🧩',
      description: 'Sphinx yang menyimpan dua petunjuk dan meminta kamu mencari nilai yang belum diketahui.',
      defeatQuote: 'Dua variabelku akhirnya kamu pecahkan!',
      maxHp: 178,
      attack: 26,
      defense: 11,
    },
    {
      id: 'mat_wali_lingkaran',
      name: 'Wali Lingkaran',
      title: 'Penguasa Jari-Jari',
      avatar: '⭕',
      description: 'Penjaga bundar yang menguji keliling, luas, dan hubungan antara diameter dengan jari-jari.',
      defeatQuote: 'Lingkaranku berputar mengikuti logikamu!',
      maxHp: 150,
      attack: 23,
      defense: 13,
    },
  ],
  'mat_naga_peluang': [
    {
      id: 'mat_phantom_kuadrat',
      name: 'Hantu Persamaan Kuadrat',
      title: 'Pemburu Akar Persamaan',
      avatar: '👻',
      description: 'Hantu yang muncul dari dua akar persamaan dan suka menyamarkan faktornya.',
      defeatQuote: 'Akar-akarku sudah ditemukan!',
      maxHp: 300,
      attack: 40,
      defense: 20,
    },
    {
      id: 'mat_orakel_transformasi',
      name: 'Orakel Transformasi',
      title: 'Pengubah Titik dan Bangun',
      avatar: '🔄',
      description: 'Orakel yang memindahkan, mencerminkan, dan memperbesar bangun di bidang koordinat.',
      defeatQuote: 'Transformasiku berubah menjadi pelajaran!',
      maxHp: 340,
      attack: 44,
      defense: 17,
    },
  ],
  'ipa_spora_mikroba': [
    {
      id: 'ipa_alchemist_materi',
      name: 'Alkemis Perubahan Zat',
      title: 'Pengolah Campuran dan Reaksi',
      avatar: '⚗️',
      description: 'Alkemis yang mencampur zat dan menguji apakah perubahan yang terjadi bersifat fisika atau kimia.',
      defeatQuote: 'Campuranku berubah karena percobaanmu!',
      maxHp: 82,
      attack: 12,
      defense: 4,
    },
    {
      id: 'ipa_penjaga_ekosistem',
      name: 'Penjaga Rantai Makanan',
      title: 'Pengatur Keseimbangan Alam',
      avatar: '🌿',
      description: 'Penjaga hutan yang menghubungkan produsen, konsumen, dan pengurai dalam satu ekosistem.',
      defeatQuote: 'Keseimbangan alam kembali terjaga!',
      maxHp: 96,
      attack: 13,
      defense: 5,
    },
  ],
  'ipa_titan_gravitasi': [
    {
      id: 'ipa_colossus_tekanan',
      name: 'Kolossus Tekanan',
      title: 'Pengendali Gaya pada Permukaan',
      avatar: '🪨',
      description: 'Raksasa yang menekan benda padat, cair, dan gas untuk menguji pemahamanmu.',
      defeatQuote: 'Tekananku kalah oleh perhitunganmu!',
      maxHp: 205,
      attack: 30,
      defense: 13,
    },
    {
      id: 'ipa_druid_tumbuhan',
      name: 'Druid Jaringan Tumbuhan',
      title: 'Penjaga Akar dan Daun',
      avatar: '🌳',
      description: 'Druid yang menghidupkan jaringan akar, batang, dan daun untuk menguji fungsi tiap bagian.',
      defeatQuote: 'Jaringanku tumbuh bersama pengetahuanmu!',
      maxHp: 180,
      attack: 27,
      defense: 14,
    },
  ],
  'ipa_cyber_atom': [
    {
      id: 'ipa_magnet_colossus',
      name: 'Kolossus Medan Magnet',
      title: 'Pengarah Kutub Utara dan Selatan',
      avatar: '🧲',
      description: 'Robot raksasa yang memutar garis medan magnet dan elektromagnet.',
      defeatQuote: 'Kutubku tertarik pada jawaban yang benar!',
      maxHp: 330,
      attack: 43,
      defense: 22,
    },
    {
      id: 'ipa_mutan_genetika',
      name: 'Mutan Pewarisan Sifat',
      title: 'Penjaga Gen dan Kromosom',
      avatar: '🧬',
      description: 'Makhluk hasil persilangan yang menguji gen dominan, resesif, dan variasi keturunan.',
      defeatQuote: 'Sifat unggulmu diwariskan ke ronde berikutnya!',
      maxHp: 370,
      attack: 47,
      defense: 19,
    },
  ],
  'ips_bayangan_arkeolog': [
    {
      id: 'ips_pemandu_peta',
      name: 'Pemandu Peta Nusantara',
      title: 'Pembaca Simbol dan Skala',
      avatar: '🗺️',
      description: 'Pemandu perjalanan yang menyembunyikan arah dan jarak di dalam peta.',
      defeatQuote: 'Arah perjalananmu sudah tepat!',
      maxHp: 98,
      attack: 15,
      defense: 5,
    },
    {
      id: 'ips_ratu_kelangkaan',
      name: 'Ratu Kelangkaan',
      title: 'Pengatur Kebutuhan dan Pilihan',
      avatar: '⚖️',
      description: 'Ratu pasar yang membuat sumber daya terbatas dan memintamu menentukan pilihan paling masuk akal.',
      defeatQuote: 'Pilihanmu bijak di tengah kelangkaan!',
      maxHp: 110,
      attack: 16,
      defense: 6,
    },
  ],
  'ips_pendekar_majapahit': [
    {
      id: 'ips_laksamana_barat',
      name: 'Laksamana Jalur Rempah',
      title: 'Pengawal Kedatangan Bangsa Barat',
      avatar: '⛵',
      description: 'Laksamana yang membawa peta pelayaran dan cerita tentang perubahan Nusantara.',
      defeatQuote: 'Jalur rempah kini kamu pahami!',
      maxHp: 235,
      attack: 34,
      defense: 15,
    },
    {
      id: 'ips_shifter_mobilitas',
      name: 'Pengubah Status Sosial',
      title: 'Penjelajah Mobilitas Masyarakat',
      avatar: '🪜',
      description: 'Petualang yang berpindah lapisan sosial dan menantangmu membaca faktor pendorongnya.',
      defeatQuote: 'Langkah sosialmu berhasil naik tingkat!',
      maxHp: 210,
      attack: 31,
      defense: 16,
    },
  ],
  'ips_baron_monopoli': [
    {
      id: 'ips_diplomat_global',
      name: 'Diplomat Kerja Sama Dunia',
      title: 'Penghubung Antarnegara',
      avatar: '🌐',
      description: 'Diplomat yang menguji kerja sama internasional dan peran Indonesia di dunia.',
      defeatQuote: 'Kerja samamu membuka jalan baru!',
      maxHp: 330,
      attack: 42,
      defense: 18,
    },
    {
      id: 'ips_reformasi_sosial',
      name: 'Raksasa Perubahan Sosial',
      title: 'Pengguncang Kebiasaan Lama',
      avatar: '🏙️',
      description: 'Raksasa kota yang membawa perubahan teknologi, budaya, dan tantangan pembangunan.',
      defeatQuote: 'Perubahan kali ini membawa kemajuan!',
      maxHp: 290,
      attack: 39,
      defense: 21,
    },
  ],
  'indo_mimik_kata': [
    {
      id: 'indo_narasi_fantasi',
      name: 'Naga Cerita Fantasi',
      title: 'Penguasa Tokoh dan Alur',
      avatar: '🐉',
      description: 'Naga yang menyusun tokoh, latar, dan kejadian ajaib menjadi cerita yang seru.',
      defeatQuote: 'Alur ceritaku berakhir dengan pemahamanmu!',
      maxHp: 94,
      attack: 14,
      defense: 5,
    },
    {
      id: 'indo_editor_eyd',
      name: 'Editor Ejaan',
      title: 'Penjaga Huruf Kapital',
      avatar: '✏️',
      description: 'Editor yang menyisipkan kesalahan ejaan dan tanda baca untuk kamu rapikan.',
      defeatQuote: 'Kalimatmu sudah rapi dan mudah dibaca!',
      maxHp: 78,
      attack: 12,
      defense: 4,
    },
  ],
  'indo_penyair_majas': [
    {
      id: 'indo_jurnalis_berita',
      name: 'Jurnalis Teks Berita',
      title: 'Pemburu Fakta dan 5W1H',
      avatar: '📰',
      description: 'Jurnalis yang menyamarkan fakta, judul, dan informasi penting di balik sebuah berita.',
      defeatQuote: 'Beritaku sudah kamu cek faktanya!',
      maxHp: 215,
      attack: 31,
      defense: 13,
    },
    {
      id: 'indo_sphinx_eksposisi',
      name: 'Sphinx Teks Eksposisi',
      title: 'Penjaga Tesis dan Argumen',
      avatar: '🗿',
      description: 'Sphinx yang meminta alasan, bukti, dan penegasan ulang untuk memperkuat pendapat.',
      defeatQuote: 'Argumenmu tersusun kuat!',
      maxHp: 190,
      attack: 29,
      defense: 14,
    },
  ],
  'indo_raja_cerpen': [
    {
      id: 'indo_orator_persuasif',
      name: 'Orator Pidato Persuasif',
      title: 'Penggerak Aksi Positif',
      avatar: '🎙️',
      description: 'Orator yang menyusun pembukaan, alasan, dan ajakan agar pendengar mau bertindak.',
      defeatQuote: 'Ajakanmu terdengar meyakinkan!',
      maxHp: 355,
      attack: 45,
      defense: 20,
    },
    {
      id: 'indo_kritikus_resensi',
      name: 'Kritikus Resensi Buku',
      title: 'Penilai Karya Sastra',
      avatar: '📚',
      description: 'Kritikus yang menguji ringkasan, kelebihan, kekurangan, dan rekomendasi sebuah karya.',
      defeatQuote: 'Penilaianmu adil dan beralasan!',
      maxHp: 325,
      attack: 42,
      defense: 22,
    },
  ],
  'eng_sprite_grammar': [
    {
      id: 'eng_descriptive_pixie',
      name: 'Descriptive Pixie',
      title: 'Keeper of Clear Details',
      avatar: '🧚',
      description: 'A bright pixie testing adjectives and simple descriptions of people, places, and things.',
      defeatQuote: 'Your description is clear and vivid!',
      maxHp: 96,
      attack: 15,
      defense: 5,
    },
    {
      id: 'eng_present_guardian',
      name: 'Present Tense Guardian',
      title: 'Watcher of Daily Habits',
      avatar: '⏰',
      description: 'A clock guardian checking verbs, routines, and facts in the simple present tense.',
      defeatQuote: 'Your verb agreement is right on time!',
      maxHp: 80,
      attack: 12,
      defense: 5,
    },
  ],
  'eng_gargoyle_narrative': [
    {
      id: 'eng_modal_knight',
      name: 'Modal Auxiliary Knight',
      title: 'Guardian of Advice and Ability',
      avatar: '🛡️',
      description: 'A knight who asks when to use can, should, must, and may in everyday situations.',
      defeatQuote: 'Your advice is grammatically sound!',
      maxHp: 225,
      attack: 34,
      defense: 15,
    },
    {
      id: 'eng_recount_witch',
      name: 'Recount Story Witch',
      title: 'Keeper of Past Experiences',
      avatar: '🧙',
      description: 'A friendly witch mixing time order and past verbs in a personal recount.',
      defeatQuote: 'Your past-tense story is well ordered!',
      maxHp: 195,
      attack: 31,
      defense: 13,
    },
  ],
  'eng_dragon_vocabulary': [
    {
      id: 'eng_report_titan',
      name: 'Report Text Titan',
      title: 'Master of General Facts',
      avatar: '🦕',
      description: 'A titan testing facts, classification, and the structure of report texts.',
      defeatQuote: 'Your facts are accurate and well organized!',
      maxHp: 375,
      attack: 48,
      defense: 23,
    },
    {
      id: 'eng_conjunction_dragon',
      name: 'Purpose Conjunction Dragon',
      title: 'Keeper of Logical Links',
      avatar: '🐲',
      description: 'A dragon connecting ideas with because, although, so that, and in order to.',
      defeatQuote: 'Your ideas connect perfectly!',
      maxHp: 345,
      attack: 44,
      defense: 21,
    },
  ],
};

const VARIANT_ENEMIES: Enemy[] = Object.entries(ENEMY_VARIANT_CONFIGS).flatMap(([baseId, variants]) => {
  const base = BASE_ENEMY_DATABASE.find((enemy) => enemy.id === baseId);
  if (!base) return [];

  return variants.map((variant) => ({
    ...base,
    ...variant,
    hp: variant.maxHp ?? base.maxHp,
    maxHp: variant.maxHp ?? base.maxHp,
    attack: variant.attack ?? base.attack,
    defense: variant.defense ?? base.defense,
    possibleDrops: base.possibleDrops.map((drop) => ({ ...drop })),
  }));
});

export const ENEMY_DATABASE: Enemy[] = [...BASE_ENEMY_DATABASE, ...VARIANT_ENEMIES];

export function getEnemiesBySubject(subject: Subject, grade?: GradeLevel): Enemy[] {
  return ENEMY_DATABASE.filter((enemy) => {
    if (enemy.subject !== subject) return false;
    if (grade && enemy.grade !== grade) return false;
    return true;
  });
}

export function getRandomEnemy(subject: Subject, grade: GradeLevel = 7, excludeIds: string[] = []): Enemy {
  const matching = getEnemiesBySubject(subject, grade);
  const available = matching.filter((enemy) => !excludeIds.includes(enemy.id));
  const pool = available.length > 0 ? available : matching;
  if (pool.length > 0) {
    const selected = pool[Math.floor(Math.random() * pool.length)];
    // Clone so HP from one wave never leaks into another wave.
    return {
      ...selected,
      hp: selected.maxHp,
      possibleDrops: selected.possibleDrops.map((drop) => ({ ...drop })),
    };
  }

  // Fallback ke mapel yang sama jika kombinasi kelas belum punya data.
  const anySubject = ENEMY_DATABASE.filter((enemy) => enemy.subject === subject);
  const picked = anySubject[0] || ENEMY_DATABASE[0];
  return {
    ...picked,
    hp: picked.maxHp,
    possibleDrops: picked.possibleDrops.map((drop) => ({ ...drop })),
  };
}
