import { Enemy, Subject, GradeLevel } from '@/types/game';

export const ENEMY_DATABASE: Enemy[] = [
  // === MATEMATIKA ===
  {
    id: 'mat_slime_rumus',
    name: 'Slime Rumus Aljabar',
    title: 'Penjaga Persamaan Linier',
    subject: 'matematika',
    grade: 7,
    level: 1,
    maxHp: 80,
    hp: 80,
    attack: 12,
    defense: 4,
    avatar: '📐',
    elementColor: '#E06C75',
    description: 'Makhluk lendir yang terbentuk dari kumpulan variabel x dan y yang belum terpecahkan.',
    defeatQuote: 'Variabelku akhirnya terdefinisikan...',
    expReward: 45,
    goldReward: 25,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'weapon_wooden_ruler', dropChance: 0.15 },
    ],
  },
  {
    id: 'mat_golem_pythagoras',
    name: 'Golem Pythagoras Segitiga',
    title: 'Penjaga Sisi Miring Hipotenusa',
    subject: 'matematika',
    grade: 8,
    level: 4,
    maxHp: 160,
    hp: 160,
    attack: 24,
    defense: 10,
    avatar: '🔺',
    elementColor: '#E06C75',
    description: 'Monster batu padat yang tersusun dari rumus a² + b² = c².',
    defeatQuote: 'Sudut siku-sikuku runtuh oleh logikamu!',
    expReward: 95,
    goldReward: 55,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'buff_defense', dropChance: 0.3 },
    ],
  },
  {
    id: 'mat_naga_peluang',
    name: 'Naga Statistika & Peluang',
    title: 'Penguasa Distribusi Data',
    subject: 'matematika',
    grade: 9,
    level: 8,
    maxHp: 320,
    hp: 320,
    attack: 42,
    defense: 18,
    avatar: '🐲',
    elementColor: '#E06C75',
    description: 'Naga legendaris yang menyemburkan api probabilitas dan diagram batang raksasa.',
    defeatQuote: 'Peluang kekalahanku ternyata 100% di hadapanmu!',
    expReward: 220,
    goldReward: 130,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.3 },
      { itemId: 'weapon_calculus_staff', dropChance: 0.1 },
    ],
  },

  // === IPA (ILMU PENGETAHUAN ALAM) ===
  {
    id: 'ipa_spora_mikroba',
    name: 'Spora Mikroorganisme Liar',
    title: 'Entitas Sel Uniseluler',
    subject: 'ipa',
    grade: 7,
    level: 1,
    maxHp: 75,
    hp: 75,
    attack: 11,
    defense: 3,
    avatar: '🦠',
    elementColor: '#98C379',
    description: 'Koloni mikroba bersel tunggal yang aktif melakukan pembelahan biner tak terkontrol.',
    defeatQuote: 'Membran selku pecah oleh sainsmu...',
    expReward: 42,
    goldReward: 22,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'buff_attack', dropChance: 0.2 },
    ],
  },
  {
    id: 'ipa_titan_gravitasi',
    name: 'Titan Hukum Newton',
    title: 'Pengendali Gaya Aksi-Reaksi',
    subject: 'ipa',
    grade: 8,
    level: 5,
    maxHp: 190,
    hp: 190,
    attack: 28,
    defense: 12,
    avatar: '🪐',
    elementColor: '#98C379',
    description: 'Raksasa kosmik yang memanfaatkan percepatan gravitasi dan inersia massa.',
    defeatQuote: 'Setiap aksi memang menghasilkan reaksi balik yang setimpal...',
    expReward: 120,
    goldReward: 65,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'scroll_hint', dropChance: 0.35 },
    ],
  },
  {
    id: 'ipa_cyber_atom',
    name: 'Raja Reaktor Listrik Dinamis',
    title: 'Pembangkit Muatan Elektronik',
    subject: 'ipa',
    grade: 9,
    level: 9,
    maxHp: 350,
    hp: 350,
    attack: 45,
    defense: 20,
    avatar: '⚡',
    elementColor: '#98C379',
    description: 'Robot generator bertegangan tinggi yang memancarkan arus searah dan bolak-balik.',
    defeatQuote: 'Arus listrikku telah dinetralkan!',
    expReward: 250,
    goldReward: 150,
    possibleDrops: [
      { itemId: 'potion_hp_large', dropChance: 0.6 },
      { itemId: 'armor_lab_coat', dropChance: 0.2 },
    ],
  },

  // === IPS (ILMU PENGETAHUAN SOSIAL) ===
  {
    id: 'ips_bayangan_arkeolog',
    name: 'Roh Penjelajah Peta Kuno',
    title: 'Penjaga Garis Lintang & Bujur',
    subject: 'ips',
    grade: 7,
    level: 2,
    maxHp: 90,
    hp: 90,
    attack: 14,
    defense: 5,
    avatar: '🧭',
    elementColor: '#D19A66',
    description: 'Roh penjelajah samudra yang tersesat di peta skala besar tanpa kompas yang tepat.',
    defeatQuote: 'Koordinat pemahamanku kini menjadi jelas...',
    expReward: 55,
    goldReward: 30,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.5 },
      { itemId: 'scroll_hint', dropChance: 0.25 },
    ],
  },
  {
    id: 'ips_pendekar_majapahit',
    name: 'Kesatria Benteng Nusantara',
    title: 'Pelindung Jalur Rempah Maritim',
    subject: 'ips',
    grade: 8,
    level: 6,
    maxHp: 220,
    hp: 220,
    attack: 32,
    defense: 15,
    avatar: '🛡️',
    elementColor: '#D19A66',
    description: 'Prajurit pelindung sejarah kerajaan masa lampau yang menguji wawasan kebangsaan.',
    defeatQuote: 'Semangat Sumpah Palapa hidup dalam jiwamu!',
    expReward: 140,
    goldReward: 80,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'armor_school_vest', dropChance: 0.25 },
    ],
  },
  {
    id: 'ips_baron_monopoli',
    name: 'Baron Perdagangan Internasional',
    title: 'Penguasa Valuta Asing & Inflasi',
    subject: 'ips',
    grade: 9,
    level: 8,
    maxHp: 310,
    hp: 310,
    attack: 40,
    defense: 19,
    avatar: '💰',
    elementColor: '#D19A66',
    description: 'Konglomerat bayangan yang memanipulasi hukum permintaan, penawaran, dan pasar global.',
    defeatQuote: 'Kebijakan ekonomimu meruntuhkan monopoliku!',
    expReward: 230,
    goldReward: 180,
    possibleDrops: [
      { itemId: 'talisman_exp', dropChance: 0.4 },
      { itemId: 'potion_hp_large', dropChance: 0.5 },
    ],
  },

  // === BAHASA INDONESIA ===
  {
    id: 'indo_mimik_kata',
    name: 'Mimik Tanda Baca',
    title: 'Pengacau Huruf Kapital & Koma',
    subject: 'indonesia',
    grade: 7,
    level: 2,
    maxHp: 85,
    hp: 85,
    attack: 13,
    defense: 4,
    avatar: '🖋️',
    elementColor: '#61AFEF',
    description: 'Monster lincah yang suka menukar tanda titik koma dan menghilangkan konjungsi penting.',
    defeatQuote: 'Kalimatmu tersusun rapi sesuai EYD...',
    expReward: 50,
    goldReward: 28,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'scroll_hint', dropChance: 0.3 },
    ],
  },
  {
    id: 'indo_penyair_majas',
    name: 'Penyair Majas & Perumpamaan',
    title: 'Penutur Metafora Gelap',
    subject: 'indonesia',
    grade: 8,
    level: 5,
    maxHp: 200,
    hp: 200,
    attack: 30,
    defense: 12,
    avatar: '📜',
    elementColor: '#61AFEF',
    description: 'Penyair misterius yang menyerang dengan larik puisi personifikasi dan hiperbola memukau.',
    defeatQuote: 'Amanat bait puisimu meluluhkan hatiku!',
    expReward: 130,
    goldReward: 70,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'weapon_pen_blade', dropChance: 0.15 },
    ],
  },
  {
    id: 'indo_raja_cerpen',
    name: 'Arsitek Teks Eksplanasi & Pidato',
    title: 'Master Gagasan Pokok & Resensi',
    subject: 'indonesia',
    grade: 9,
    level: 9,
    maxHp: 340,
    hp: 340,
    attack: 44,
    defense: 21,
    avatar: '📖',
    elementColor: '#61AFEF',
    description: 'Penjaga perpustakaan agung yang memegang rahasia struktur teks persuasif dan resensi sastra.',
    defeatQuote: 'Argumenmu tak terbantahkan secara logis!',
    expReward: 240,
    goldReward: 140,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.3 },
      { itemId: 'armor_archmage_robe', dropChance: 0.08 },
    ],
  },

  // === BAHASA INGGRIS ===
  {
    id: 'eng_sprite_grammar',
    name: 'Past Tense Sprite',
    title: 'Irregular Verbs Mischief',
    subject: 'inggris',
    grade: 7,
    level: 2,
    maxHp: 88,
    hp: 88,
    attack: 14,
    defense: 4,
    avatar: '🔤',
    elementColor: '#C678DD',
    description: 'A swift fairy confusing simple present and past tense auxiliary verbs (did, was, were).',
    defeatQuote: 'Your grammar structure is impeccable!',
    expReward: 52,
    goldReward: 26,
    possibleDrops: [
      { itemId: 'potion_hp_small', dropChance: 0.6 },
      { itemId: 'talisman_exp', dropChance: 0.2 },
    ],
  },
  {
    id: 'eng_gargoyle_narrative',
    name: 'Narrative Fable Gargoyle',
    title: 'Keeper of Moral Lessons',
    subject: 'inggris',
    grade: 8,
    level: 6,
    maxHp: 210,
    hp: 210,
    attack: 33,
    defense: 14,
    avatar: '🦇',
    elementColor: '#C678DD',
    description: 'An ancient winged guardian asking deep questions about moral values in classic folklore.',
    defeatQuote: 'You understood the moral lesson completely...',
    expReward: 145,
    goldReward: 75,
    possibleDrops: [
      { itemId: 'potion_hp_medium', dropChance: 0.5 },
      { itemId: 'buff_attack', dropChance: 0.3 },
    ],
  },
  {
    id: 'eng_dragon_vocabulary',
    name: 'Vocabulary Sovereign Drake',
    title: 'Master of Idioms & Passive Voice',
    subject: 'inggris',
    grade: 9,
    level: 9,
    maxHp: 360,
    hp: 360,
    attack: 46,
    defense: 22,
    avatar: '🐉',
    elementColor: '#C678DD',
    description: 'A majestic bilingual dragon testing advanced synonym contextual usage and formal letters.',
    defeatQuote: 'Your vocabulary is as vast as the open ocean!',
    expReward: 260,
    goldReward: 160,
    possibleDrops: [
      { itemId: 'potion_elixir', dropChance: 0.35 },
      { itemId: 'weapon_pen_blade', dropChance: 0.2 },
    ],
  },
];

export function getEnemiesBySubject(subject: Subject, grade?: GradeLevel): Enemy[] {
  return ENEMY_DATABASE.filter((enemy) => {
    if (enemy.subject !== subject) return false;
    if (grade && enemy.grade !== grade) return false;
    return true;
  });
}

export function getRandomEnemy(subject: Subject, grade: GradeLevel = 7): Enemy {
  const matching = getEnemiesBySubject(subject, grade);
  if (matching.length > 0) {
    const selected = matching[Math.floor(Math.random() * matching.length)];
    // Deep clone to reset HP
    return {
      ...selected,
      hp: selected.maxHp,
    };
  }
  // Fallback to any matching subject
  const anySubject = ENEMY_DATABASE.filter((e) => e.subject === subject);
  const picked = anySubject[0] || ENEMY_DATABASE[0];
  return {
    ...picked,
    hp: picked.maxHp,
  };
}
