import { Question, Subject, GradeLevel } from '@/types/game';
import { formatQuestion } from '@/lib/game/question-format';
import { ADDITIONAL_QUESTION_BANK } from '@/lib/game/additional-question-bank';

export const QUESTION_BANK: Question[] = [
  // ==========================================
  // MATEMATIKA (SMP KELAS 7, 8, 9)
  // ==========================================
  {
    id: 'mat-001',
    subject: 'matematika',
    grade: 7,
    topic: 'Aljabar & Persamaan Linier',
    difficulty: 'easy',
    question: 'Kalau 3x + 7 = 22, berapa nilai x?',
    options: ['3', '5', '6', '7'],
    correctAnswer: 1, // '5'
    explanation: 'Cari x dengan mengurangi kedua ruas: 3x = 22 − 7 → 3x = 15 → x = 15 ÷ 3 = 5.',
    hint: 'Kurangi kedua ruas dengan 7, lalu bagi hasilnya dengan 3.',
    source: 'local_bank',
  },
  {
    id: 'mat-002',
    subject: 'matematika',
    grade: 7,
    topic: 'Bilangan Bulat & Pecahan',
    difficulty: 'easy',
    question: 'Berapa hasil dari (−12) + 7 × (−3)?',
    options: ['-33', '-15', '33', '-9'],
    correctAnswer: 0, // '-33'
    explanation: 'Ikuti urutan operasi: kerjakan perkalian dulu, yaitu 7 × (−3) = −21. Setelah itu, (−12) + (−21) = −33.',
    hint: 'Ingat, perkalian dikerjakan sebelum penjumlahan.',
    source: 'local_bank',
  },
  {
    id: 'mat-003',
    subject: 'matematika',
    grade: 7,
    topic: 'Himpunan',
    difficulty: 'medium',
    question: 'Diketahui S = {bilangan asli kurang dari 10} dan A = {bilangan prima kurang dari 10}. Apa komplemen A (Aᶜ)?',
    options: ['{1, 4, 6, 8, 9}', '{2, 3, 5, 7}', '{1, 3, 5, 7, 9}', '{4, 6, 8, 9}'],
    correctAnswer: 0, // '{1, 4, 6, 8, 9}'
    explanation: 'S berisi angka 1 sampai 9, sedangkan A berisi 2, 3, 5, dan 7. Jadi anggota S yang tidak ada di A adalah {1, 4, 6, 8, 9}. Ingat, 1 bukan bilangan prima.',
    hint: 'Simpan angka 1 sampai 9, lalu singkirkan 2, 3, 5, dan 7.',
    source: 'local_bank',
  },
  {
    id: 'mat-004',
    subject: 'matematika',
    grade: 8,
    topic: 'Teorema Pythagoras',
    difficulty: 'medium',
    question: 'Segitiga siku-siku punya sisi 6 cm dan 8 cm. Berapa panjang sisi miringnya (hipotenusa)?',
    options: ['9 cm', '10 cm', '12 cm', '14 cm'],
    correctAnswer: 1, // '10 cm'
    explanation: 'Pakai Teorema Pythagoras: c² = a² + b² → c² = 6² + 8² = 36 + 64 = 100. Jadi c = √100 = 10 cm.',
    hint: 'Coba mulai dari rumus c² = a² + b².',
    source: 'local_bank',
  },
  {
    id: 'mat-005',
    subject: 'matematika',
    grade: 8,
    topic: 'Sistem Persamaan Linier Dua Variabel (SPLDV)',
    difficulty: 'hard',
    question: 'Diketahui x + 2y = 8 dan 2x − y = 6. Berapa nilai x + y?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 2, // '6'
    explanation: 'Dari persamaan kedua, y = 2x − 6. Masukkan ke persamaan pertama: x + 2(2x − 6) = 8 → 5x = 20 → x = 4. Lalu y = 2(4) − 6 = 2. Jadi x + y = 6.',
    hint: 'Pakai substitusi atau eliminasi untuk menemukan x dan y.',
    source: 'local_bank',
  },
  {
    id: 'mat-006',
    subject: 'matematika',
    grade: 9,
    topic: 'Pangkat dan Bentuk Akar',
    difficulty: 'medium',
    question: 'Bentuk sederhana dari 3√5 + 2√20 - √45 adalah...',
    options: ['4√5', '5√5', '6√5', '3√5'],
    correctAnswer: 0, // '4√5'
    explanation: '√20 = √(4 × 5) = 2√5, sehingga 2√20 = 4√5. √45 = √(9 × 5) = 3√5. Maka 3√5 + 4√5 - 3√5 = 4√5.',
    hint: 'Sederhanakan √20 menjadi 2√5 dan √45 menjadi 3√5.',
    source: 'local_bank',
  },
  {
    id: 'mat-007',
    subject: 'matematika',
    grade: 9,
    topic: 'Persamaan Kuadrat',
    difficulty: 'hard',
    question: 'Akar persamaan kuadrat x² − 5x + 6 = 0 adalah ...',
    options: ['x = 1 atau x = 6', 'x = -2 atau x = -3', 'x = 2 atau x = 3', 'x = -1 atau x = -6'],
    correctAnswer: 2, // 'x = 2 atau x = 3'
    explanation: 'Faktorkan: (x − 2)(x − 3) = 0. Jadi x = 2 atau x = 3.',
    hint: 'Cari dua bilangan yang hasil kalinya 6 dan jumlahnya −5.',
    source: 'local_bank',
  },

  // ==========================================
  // IPA (ILMU PENGETAHUAN ALAM)
  // ==========================================
  {
    id: 'ipa-001',
    subject: 'ipa',
    grade: 7,
    topic: 'Organisasi Kehidupan & Sel',
    difficulty: 'easy',
    question: 'Bagian sel yang dikenal sebagai “pabrik energi” dan menjadi tempat respirasi sel adalah ...',
    options: ['Ribosom', 'Mitokondria', 'Badan Golgi', 'Kloroplas'],
    correctAnswer: 1, // 'Mitokondria'
    explanation: 'Mitokondria menjadi tempat respirasi sel untuk menghasilkan energi dalam bentuk ATP.',
    hint: 'Ingat julukannya: powerhouse of the cell atau “pembangkit energi sel”.',
    source: 'local_bank',
  },
  {
    id: 'ipa-002',
    subject: 'ipa',
    grade: 7,
    topic: 'Suhu dan Kalor',
    difficulty: 'easy',
    question: 'Suhu 40°C kalau diubah ke Fahrenheit menjadi ...',
    options: ['72°F', '96°F', '104°F', '112°F'],
    correctAnswer: 2, // '104°F'
    explanation: 'Rumus Celsius ke Fahrenheit: F = (9 ÷ 5 × C) + 32 = (9 ÷ 5 × 40) + 32 = 104°F.',
    hint: 'Pakai rumus F = (9 ÷ 5 × C) + 32.',
    source: 'local_bank',
  },
  {
    id: 'ipa-003',
    subject: 'ipa',
    grade: 8,
    topic: 'Hukum Newton',
    difficulty: 'medium',
    question: 'Benda bermassa 5 kg ditarik gaya 20 N. Berapa percepatannya?',
    options: ['2 m per s²', '4 m per s²', '15 m per s²', '100 m per s²'],
    correctAnswer: 1, // '4 m per s²'
    explanation: 'Pakai Hukum II Newton, F = m × a. Jadi a = F ÷ m = 20 N ÷ 5 kg = 4 m per s².',
    hint: 'Pakai rumus a = F ÷ m.',
    source: 'local_bank',
  },
  {
    id: 'ipa-004',
    subject: 'ipa',
    grade: 8,
    topic: 'Sistem Pencernaan Manusia',
    difficulty: 'medium',
    question: 'Enzim dari lambung yang membantu mengubah protein menjadi pepton adalah ...',
    options: ['Ptialin', 'Pepsin', 'Amilase', 'Lipase'],
    correctAnswer: 1, // 'Pepsin'
    explanation: 'Lambung menghasilkan pepsin untuk mencerna protein menjadi pepton. Lambung juga menghasilkan renin dan asam klorida (HCl).',
    hint: 'Namanya diawali huruf P dan bekerja dalam suasana asam lambung.',
    source: 'local_bank',
  },
  {
    id: 'ipa-005',
    subject: 'ipa',
    grade: 9,
    topic: 'Listrik Dinamis & Hukum Ohm',
    difficulty: 'medium',
    question: 'Lampu dengan hambatan 20 ohm dipasang pada tegangan 12 volt. Berapa kuat arusnya?',
    options: ['0,6 A', '1,67 A', '240 A', '0,4 A'],
    correctAnswer: 0, // '0,6 A'
    explanation: 'Menurut Hukum Ohm, V = I × R. Jadi I = V ÷ R = 12 V ÷ 20 Ω = 0,6 ampere.',
    hint: 'Kuat arus (I) = tegangan (V) ÷ hambatan (R).',
    source: 'local_bank',
  },
  {
    id: 'ipa-006',
    subject: 'ipa',
    grade: 9,
    topic: 'Pewarisan Sifat (Genetika)',
    difficulty: 'hard',
    question: 'Tanaman merah (MM) disilangkan dengan tanaman putih (mm), lalu F1 (Mm) disilangkan sesamanya. Berapa perbandingan fenotipe F2?',
    options: ['1 Merah : 2 Merah Muda : 1 Putih', '3 Merah : 1 Putih', '1 Merah : 3 Putih', 'Semua Berbunga Merah'],
    correctAnswer: 1, // '3 Merah : 1 Putih'
    explanation: 'Persilangan Mm × Mm menghasilkan MM (1), Mm (2), dan mm (1). Karena M dominan penuh, MM dan Mm berwarna merah. Jadi fenotipenya 3 merah : 1 putih.',
    hint: 'Pada dominan penuh, heterozigot (Mm) punya fenotipe yang sama dengan MM.',
    source: 'local_bank',
  },

  // ==========================================
  // IPS (ILMU PENGETAHUAN SOSIAL)
  // ==========================================
  {
    id: 'ips-001',
    subject: 'ips',
    grade: 7,
    topic: 'Letak Geografis Indonesia',
    difficulty: 'easy',
    question: 'Indonesia berada di antara dua benua dan dua samudra. Benua dan samudranya apa saja?',
    options: [
      'Benua Asia - Australia dan Samudra Hindia - Pasifik',
      'Benua Asia - Afrika dan Samudra Atlantik - Pasifik',
      'Benua Eropa - Asia dan Samudra Hindia - Atlantik',
      'Benua Amerika - Asia dan Samudra Arktik - Pasifik',
    ],
    correctAnswer: 0,
    explanation: 'Indonesia berada di antara Benua Asia dan Australia, serta Samudra Hindia dan Pasifik.',
    hint: 'Ingat benua di utara–selatan dan samudra di barat–timur Indonesia.',
    source: 'local_bank',
  },
  {
    id: 'ips-002',
    subject: 'ips',
    grade: 7,
    topic: 'Interaksi Sosial & Pranata Sosial',
    difficulty: 'easy',
    question: 'Interaksi sosial asosiatif berupa usaha bersama untuk mencapai tujuan bersama disebut ...',
    options: ['Akomodasi', 'Kerjasama (Kooperasi)', 'Asimilasi', 'Akulturasi'],
    correctAnswer: 1,
    explanation: 'Kerja sama terjadi saat beberapa pihak saling membantu untuk mencapai tujuan bersama.',
    hint: 'Kata kuncinya: “usaha bersama untuk mencapai tujuan”.',
    source: 'local_bank',
  },
  {
    id: 'ips-003',
    subject: 'ips',
    grade: 8,
    topic: 'Sejarah Kerajaan Hindu-Buddha Nusantara',
    difficulty: 'medium',
    question: 'Prasasti Yupa dari Muara Kaman, Kalimantan Timur, merupakan peninggalan kerajaan tertua di Indonesia, yaitu ...',
    options: ['Kerajaan Tarumanegara', 'Kerajaan Kutai', 'Kerajaan Sriwijaya', 'Kerajaan Majapahit'],
    correctAnswer: 1,
    explanation: 'Prasasti Yupa memakai aksara Pallawa dan bahasa Sanskerta. Prasasti ini berasal dari Kerajaan Kutai pada masa Raja Mulawarman, sekitar abad ke-4.',
    hint: 'Raja yang terkenal dari kerajaan ini adalah Mulawarman.',
    source: 'local_bank',
  },
  {
    id: 'ips-004',
    subject: 'ips',
    grade: 8,
    topic: 'Kerjasama Regional ASEAN',
    difficulty: 'medium',
    question: 'Deklarasi Bangkok pada 8 Agustus 1967 ditandatangani lima negara pendiri ASEAN. Siapa wakil Indonesia saat itu?',
    options: ['Ali Alatas', 'Adam Malik', 'Mohammad Hatta', 'Soedirman'],
    correctAnswer: 1,
    explanation: 'Wakil Indonesia yang menandatangani Deklarasi Bangkok adalah Menteri Luar Negeri H. Adam Malik.',
    hint: 'Tokoh ini pernah menjadi Menteri Luar Negeri dan Wakil Presiden Indonesia.',
    source: 'local_bank',
  },
  {
    id: 'ips-005',
    subject: 'ips',
    grade: 9,
    topic: 'Ekonomi Internasional & Pasar Bebas',
    difficulty: 'hard',
    question: 'Subsidi, tarif bea masuk, dan kuota impor termasuk kebijakan ...',
    options: ['Perdagangan Bebas', 'Proteksionisme Perdagangan', 'Dumping', 'Devaluasi Mata Uang'],
    correctAnswer: 1,
    explanation: 'Proteksionisme melindungi industri dalam negeri dari persaingan barang impor, misalnya lewat tarif, kuota, dan subsidi.',
    hint: 'Tujuannya melindungi industri dalam negeri.',
    source: 'local_bank',
  },

  // ==========================================
  // BAHASA INDONESIA
  // ==========================================
  {
    id: 'ind-001',
    subject: 'indonesia',
    grade: 7,
    topic: 'Teks Deskripsi',
    difficulty: 'easy',
    question: 'Teks yang menggambarkan objek dengan detail sampai pembaca seolah-olah bisa melihat atau merasakannya disebut ...',
    options: ['Teks Narasi', 'Teks Deskripsi', 'Teks Prosedur', 'Teks Eksplanasi'],
    correctAnswer: 1,
    explanation: 'Teks deskripsi menggambarkan objek dengan jelas dan detail, termasuk lewat kesan pancaindra.',
    hint: 'Kata kuncinya adalah “deskripsi”, yaitu penggambaran.',
    source: 'local_bank',
  },
  {
    id: 'ind-002',
    subject: 'indonesia',
    grade: 7,
    topic: 'Ejaan dan Tanda Baca (EYD)',
    difficulty: 'easy',
    question: 'Kalimat mana yang memakai huruf kapital dengan tepat sesuai EYD?',
    options: [
      'Ibu membeli pisang Ambon di Pasar Baru.',
      'Kami mendaki Gunung Merbabu pada hari Minggu.',
      'Pak Ahmad menjabat sebagai Gubernur sejak Tahun lalu.',
      'Suku Jawa dan suku Sunda hidup rukun di pulau jawa.',
    ],
    correctAnswer: 1,
    explanation: '“Gunung Merbabu” dan “Minggu” adalah nama diri, jadi huruf awalnya kapital. Nama jabatan umum dan jenis buah tidak selalu memakai huruf kapital.',
    hint: 'Nama tempat yang diikuti nama diri dan nama hari ditulis dengan huruf kapital.',
    source: 'local_bank',
  },
  {
    id: 'ind-003',
    subject: 'indonesia',
    grade: 8,
    topic: 'Gaya Bahasa (Majas)',
    difficulty: 'medium',
    question: '“Angin malam berbisik lembut menyampaikan kerinduanku.” Kalimat ini memakai majas ...',
    options: ['Hiperbola', 'Personifikasi', 'Metafora', 'Litotes'],
    correctAnswer: 1,
    explanation: 'Personifikasi memberi sifat manusia, seperti “berbisik”, kepada benda atau hal yang bukan manusia.',
    hint: 'Cari benda tak bernyawa yang diberi tindakan seperti manusia.',
    source: 'local_bank',
  },
  {
    id: 'ind-004',
    subject: 'indonesia',
    grade: 8,
    topic: 'Unsur Intrinsik Cerita Pendek',
    difficulty: 'medium',
    question: 'Pesan moral atau pelajaran hidup dalam karya sastra disebut ...',
    options: ['Tema', 'Latar', 'Amanat', 'Alur'],
    correctAnswer: 2,
    explanation: 'Amanat adalah pesan moral atau nasihat yang ingin disampaikan penulis lewat cerita.',
    hint: 'Ini adalah istilah untuk pesan moral dalam dongeng atau cerpen.',
    source: 'local_bank',
  },
  {
    id: 'ind-005',
    subject: 'indonesia',
    grade: 9,
    topic: 'Teks Diskusi & Gagasan Utama',
    difficulty: 'hard',
    question: 'Dalam pidato persuasif, bagian yang menegaskan lagi gagasan dan mengajak pendengar bertindak ada di ...',
    options: ['Pembukaan', 'Isi Pidato', 'Argumen Pendukung', 'Penutup'],
    correctAnswer: 3,
    explanation: 'Penutup pidato biasanya berisi simpulan, penegasan pesan, dan ajakan yang jelas kepada pendengar.',
    hint: 'Cari bagian paling akhir yang merangkum pesan dan seruan kepada pendengar.',
    source: 'local_bank',
  },

  // ==========================================
  // BAHASA INGGRIS
  // ==========================================
  {
    id: 'eng-001',
    subject: 'inggris',
    grade: 7,
    topic: 'Simple Present Tense',
    difficulty: 'easy',
    question: 'My brother usually ... to school by bicycle every morning.',
    options: ['go', 'goes', 'going', 'went'],
    correctAnswer: 1,
    explanation: '“My brother” sama dengan “he”, yaitu subjek tunggal orang ketiga. Dalam simple present, kata kerja “go” berubah menjadi “goes”.',
    hint: 'Subjek tunggal seperti he, she, atau it biasanya butuh akhiran -s atau -es.',
    source: 'local_bank',
  },
  {
    id: 'eng-002',
    subject: 'inggris',
    grade: 7,
    topic: 'Pronouns & Possessive Adjectives',
    difficulty: 'easy',
    question: 'Rina and Siti love reading. ... always visit the library during break time.',
    options: ['We', 'They', 'Them', 'Their'],
    correctAnswer: 1,
    explanation: '“Rina and Siti” berjumlah lebih dari satu orang, jadi kata gantinya sebagai subjek adalah “They”.',
    hint: 'Cari kata ganti subjek untuk “mereka”.',
    source: 'local_bank',
  },
  {
    id: 'eng-003',
    subject: 'inggris',
    grade: 8,
    topic: 'Simple Past Tense',
    difficulty: 'medium',
    question: 'We ... an interesting historical museum in Yogyakarta last holiday.',
    options: ['visit', 'visited', 'have visited', 'visiting'],
    correctAnswer: 1,
    explanation: '“Last holiday” menunjukkan waktu lampau, jadi gunakan bentuk lampau (V2), yaitu “visited”.',
    hint: 'Perhatikan “last holiday”, yang menunjukkan kejadian masa lampau.',
    source: 'local_bank',
  },
  {
    id: 'eng-004',
    subject: 'inggris',
    grade: 8,
    topic: 'Degrees of Comparison',
    difficulty: 'medium',
    question: 'Mount Everest is ... mountain in the world.',
    options: ['the highest', 'higher', 'highest', 'more high'],
    correctAnswer: 0,
    explanation: 'Karena Mount Everest dibandingkan dengan semua gunung lain, gunakan bentuk superlatif “the highest”.',
    hint: 'Untuk makna “paling tinggi”, gunakan “the” + bentuk superlatif “highest”.',
    source: 'local_bank',
  },
  {
    id: 'eng-005',
    subject: 'inggris',
    grade: 9,
    topic: 'Passive Voice',
    difficulty: 'hard',
    question: 'Transform to passive voice: "Alexander Graham Bell invented the telephone in 1876."',
    options: [
      'The telephone is invented by Alexander Graham Bell in 1876.',
      'The telephone was invented by Alexander Graham Bell in 1876.',
      'The telephone has been invented by Alexander Graham Bell in 1876.',
      'The telephone was being invented by Alexander Graham Bell in 1876.',
    ],
    correctAnswer: 1,
    explanation: '“Invented” menunjukkan simple past. Bentuk pasifnya memakai objek + was/were + V3, sehingga menjadi “The telephone was invented by Alexander Graham Bell in 1876.”',
    hint: 'Pakai “was” lalu kata kerja bentuk ketiga (V3).',
    source: 'local_bank',
  },
  {
    id: 'eng-006',
    subject: 'inggris',
    grade: 9,
    topic: 'Conjunctions (So that atau In order to)',
    difficulty: 'hard',
    question: 'We should exercise regularly ... stay healthy and active.',
    options: ['in order to', 'so that', 'because', 'although'],
    correctAnswer: 0,
    explanation: '“In order to” diikuti kata kerja dasar, seperti “stay”. Sementara itu, “so that” biasanya diikuti klausa lengkap.',
    hint: 'Gunakan “in order to” sebelum kata kerja dasar.',
    source: 'local_bank',
  },
  {
    id: 'mat-008',
    subject: 'matematika',
    grade: 7,
    topic: 'Perbandingan dan Skala',
    difficulty: 'medium',
    question: 'Resep minuman memakai perbandingan sirup dan air 2 : 5. Kalau airnya 15 gelas, berapa gelas sirup yang diperlukan?',
    options: ['4 gelas', '6 gelas', '8 gelas', '10 gelas'],
    correctAnswer: 1,
    explanation: 'Air 5 bagian menjadi 15 gelas, berarti dikali 3. Sirupnya juga 2 × 3 = 6 gelas.',
    hint: 'Cari dulu pengali dari 5 bagian menjadi 15 gelas.',
    source: 'local_bank',
  },
  {
    id: 'mat-009',
    subject: 'matematika',
    grade: 7,
    topic: 'Geometri dan Pengukuran',
    difficulty: 'easy',
    question: 'Sebuah taman berbentuk persegi panjang panjangnya 12 m dan lebarnya 7 m. Berapa keliling taman itu?',
    options: ['19 m', '38 m', '84 m', '96 m'],
    correctAnswer: 1,
    explanation: 'Keliling persegi panjang = 2 × (panjang + lebar) = 2 × (12 + 7) = 38 m.',
    hint: 'Jumlahkan panjang dan lebar, lalu kalikan hasilnya dengan 2.',
    source: 'local_bank',
  },
  {
    id: 'mat-010',
    subject: 'matematika',
    grade: 8,
    topic: 'Pola dan Barisan Bilangan',
    difficulty: 'easy',
    question: 'Barisan 4, 7, 10, 13, ... bertambah dengan pola yang sama. Angka berikutnya adalah ...',
    options: ['15', '16', '17', '18'],
    correctAnswer: 1,
    explanation: 'Setiap angka bertambah 3. Jadi angka setelah 13 adalah 13 + 3 = 16.',
    hint: 'Bandingkan selisih 4 ke 7, 7 ke 10, dan 10 ke 13.',
    source: 'local_bank',
  },
  {
    id: 'mat-011',
    subject: 'matematika',
    grade: 8,
    topic: 'Statistika',
    difficulty: 'medium',
    question: 'Nilai lima kuis adalah 6, 8, 7, 9, dan 10. Berapa nilai rata-ratanya?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    explanation: 'Jumlah semua nilai = 40. Karena ada 5 nilai, rata-ratanya 40 ÷ 5 = 8.',
    hint: 'Jumlahkan semua nilai, lalu bagi dengan banyak data.',
    source: 'local_bank',
  },
  {
    id: 'mat-012',
    subject: 'matematika',
    grade: 9,
    topic: 'Transformasi Geometri',
    difficulty: 'medium',
    question: 'Titik P(2, −1) dicerminkan terhadap sumbu y. Koordinat P’ adalah ...',
    options: ['(2, 1)', '(−2, −1)', '(−2, 1)', '(1, −2)'],
    correctAnswer: 1,
    explanation: 'Pencerminan terhadap sumbu y mengubah tanda koordinat x, sedangkan y tetap. Jadi (2, −1) menjadi (−2, −1).',
    hint: 'Pada cermin sumbu y, hanya tanda x yang berubah.',
    source: 'local_bank',
  },
  {
    id: 'mat-013',
    subject: 'matematika',
    grade: 9,
    topic: 'Peluang dan Statistika',
    difficulty: 'easy',
    question: 'Di dalam kantong ada 3 kelereng merah dan 2 kelereng biru. Peluang mengambil kelereng biru adalah ...',
    options: ['1 ÷ 5', '2 ÷ 5', '3 ÷ 5', '2 ÷ 3'],
    correctAnswer: 1,
    explanation: 'Total kelereng ada 5 dan yang biru ada 2. Jadi peluangnya 2 ÷ 5.',
    hint: 'Peluang = banyak hasil yang diinginkan ÷ seluruh kemungkinan.',
    source: 'local_bank',
  },
  {
    id: 'ipa-007',
    subject: 'ipa',
    grade: 7,
    topic: 'Klasifikasi Makhluk Hidup',
    difficulty: 'easy',
    question: 'Makhluk hidup yang tidak bisa membuat makanan sendiri dan memperoleh makanan dari organisme lain disebut ...',
    options: ['Autotrof', 'Heterotrof', 'Produsen', 'Klorofil'],
    correctAnswer: 1,
    explanation: 'Heterotrof mendapatkan makanan dari organisme lain. Hewan dan manusia termasuk kelompok ini.',
    hint: 'Lawan dari autotrof adalah organisme yang bergantung pada makhluk hidup lain untuk makanan.',
    source: 'local_bank',
  },
  {
    id: 'ipa-008',
    subject: 'ipa',
    grade: 7,
    topic: 'Pengukuran',
    difficulty: 'easy',
    question: 'Panjang meja 2,5 m. Kalau ditulis dalam sentimeter, panjangnya menjadi ...',
    options: ['25 cm', '250 cm', '2.500 cm', '0,25 cm'],
    correctAnswer: 1,
    explanation: 'Satu meter = 100 cm, jadi 2,5 × 100 = 250 cm.',
    hint: 'Dari meter ke sentimeter, kalikan dengan 100.',
    source: 'local_bank',
  },
  {
    id: 'ipa-009',
    subject: 'ipa',
    grade: 8,
    topic: 'Tekanan',
    difficulty: 'medium',
    question: 'Gaya 100 N bekerja pada bidang seluas 2 m². Berapa tekanan yang dihasilkan?',
    options: ['20 Pa', '50 Pa', '100 Pa', '200 Pa'],
    correctAnswer: 1,
    explanation: 'Tekanan = gaya ÷ luas bidang = 100 ÷ 2 = 50 Pa.',
    hint: 'Gunakan rumus tekanan = gaya ÷ luas.',
    source: 'local_bank',
  },
  {
    id: 'ipa-010',
    subject: 'ipa',
    grade: 8,
    topic: 'Usaha dan Pesawat Sederhana',
    difficulty: 'easy',
    question: 'Sebuah benda didorong dengan gaya 20 N sejauh 3 m searah gaya. Berapa usaha yang dilakukan?',
    options: ['6 J', '23 J', '60 J', '80 J'],
    correctAnswer: 2,
    explanation: 'Usaha = gaya × perpindahan = 20 × 3 = 60 joule.',
    hint: 'Kalau gaya dan perpindahan searah, kalikan keduanya.',
    source: 'local_bank',
  },
  {
    id: 'ipa-011',
    subject: 'ipa',
    grade: 9,
    topic: 'Kemagnetan dan Elektromagnet',
    difficulty: 'easy',
    question: 'Apa yang terjadi kalau dua kutub magnet yang sama didekatkan?',
    options: ['Saling tarik-menarik', 'Saling tolak-menolak', 'Tidak ada gaya', 'Keduanya kehilangan magnet'],
    correctAnswer: 1,
    explanation: 'Kutub magnet yang sama saling menolak, sedangkan kutub yang berbeda saling menarik.',
    hint: 'Ingat pasangan sederhana: senama menolak, tidak senama menarik.',
    source: 'local_bank',
  },
  {
    id: 'ipa-012',
    subject: 'ipa',
    grade: 9,
    topic: 'Bioteknologi',
    difficulty: 'easy',
    question: 'Mikroorganisme yang membantu fermentasi kedelai menjadi tempe adalah ...',
    options: ['Rhizopus', 'Plasmodium', 'Lactobacillus', 'Anopheles'],
    correctAnswer: 0,
    explanation: 'Jamur Rhizopus membantu proses fermentasi kedelai hingga terbentuk tempe.',
    hint: 'Nama jamurnya sering tertulis pada pelajaran bioteknologi konvensional.',
    source: 'local_bank',
  },
  {
    id: 'ips-006',
    subject: 'ips',
    grade: 7,
    topic: 'Peta dan Skala',
    difficulty: 'medium',
    question: 'Pada peta berskala 1 : 100.000, jarak dua kota adalah 3 cm. Berapa jarak sebenarnya?',
    options: ['300 m', '3 km', '30 km', '300 km'],
    correctAnswer: 1,
    explanation: '3 cm di peta = 3 × 100.000 cm = 300.000 cm = 3 km.',
    hint: 'Ubah hasil sentimeter ke kilometer setelah mengalikan dengan skala.',
    source: 'local_bank',
  },
  {
    id: 'ips-007',
    subject: 'ips',
    grade: 7,
    topic: 'Kebutuhan dan Kelangkaan',
    difficulty: 'medium',
    question: 'Dina punya uang untuk membeli buku atau menonton film. Ia memilih buku. Film yang tidak jadi ditonton disebut ...',
    options: ['Kebutuhan primer', 'Biaya peluang', 'Distribusi', 'Produksi'],
    correctAnswer: 1,
    explanation: 'Biaya peluang adalah pilihan terbaik yang harus dilepas saat kita mengambil pilihan lain. Di sini, film menjadi pilihan yang dilepas.',
    hint: 'Pikirkan tentang kesempatan yang hilang karena memilih sesuatu.',
    source: 'local_bank',
  },
  {
    id: 'ips-008',
    subject: 'ips',
    grade: 8,
    topic: 'Kedatangan Bangsa Barat',
    difficulty: 'easy',
    question: 'Salah satu alasan utama bangsa Barat datang ke Nusantara pada masa lalu adalah mencari ...',
    options: ['Rempah-rempah', 'Salju', 'Gurun pasir', 'Minyak bumi modern'],
    correctAnswer: 0,
    explanation: 'Rempah-rempah Nusantara sangat berharga di pasar dunia, sehingga bangsa Barat berlomba mencari sumbernya.',
    hint: 'Cengkih dan pala adalah contoh hasil Nusantara yang banyak dicari.',
    source: 'local_bank',
  },
  {
    id: 'ips-009',
    subject: 'ips',
    grade: 8,
    topic: 'Mobilitas Sosial',
    difficulty: 'medium',
    question: 'Seorang anak petani menjadi dokter setelah menyelesaikan pendidikan. Contoh ini termasuk mobilitas sosial ...',
    options: ['Horizontal', 'Vertikal naik', 'Vertikal turun', 'Geografis saja'],
    correctAnswer: 1,
    explanation: 'Status sosialnya meningkat dari kondisi awal, jadi ini disebut mobilitas vertikal naik.',
    hint: 'Status orang tersebut bergerak ke tingkat yang lebih tinggi.',
    source: 'local_bank',
  },
  {
    id: 'ips-010',
    subject: 'ips',
    grade: 9,
    topic: 'Perubahan Sosial Budaya',
    difficulty: 'easy',
    question: 'Penggunaan internet yang membuat orang berkomunikasi lebih cepat merupakan contoh perubahan sosial karena perkembangan ...',
    options: ['Teknologi', 'Cuaca', 'Bentuk muka bumi', 'Musim panen'],
    correctAnswer: 0,
    explanation: 'Internet adalah hasil perkembangan teknologi dan mengubah cara orang berkomunikasi serta bekerja.',
    hint: 'Cari faktor yang melahirkan internet dan gawai.',
    source: 'local_bank',
  },
  {
    id: 'ips-011',
    subject: 'ips',
    grade: 9,
    topic: 'Perdagangan Internasional',
    difficulty: 'easy',
    question: 'Kegiatan menjual barang dari dalam negeri ke negara lain disebut ...',
    options: ['Impor', 'Ekspor', 'Konsumsi', 'Barter lokal'],
    correctAnswer: 1,
    explanation: 'Ekspor berarti menjual atau mengirim barang ke luar negeri. Impor berarti membeli dari luar negeri.',
    hint: 'Ekspor = barang keluar dari negara kita.',
    source: 'local_bank',
  },
  {
    id: 'ind-006',
    subject: 'indonesia',
    grade: 7,
    topic: 'Teks Prosedur',
    difficulty: 'easy',
    question: 'Bagian teks prosedur yang menjelaskan hasil akhir atau hal yang ingin dicapai disebut ...',
    options: ['Tujuan', 'Bahan', 'Langkah-langkah', 'Penutup surat'],
    correctAnswer: 0,
    explanation: 'Tujuan memberi tahu pembaca apa yang akan dibuat atau dilakukan lewat prosedur tersebut.',
    hint: 'Bagian ini biasanya muncul di awal dan menjawab pertanyaan “mau membuat apa?”.',
    source: 'local_bank',
  },
  {
    id: 'ind-007',
    subject: 'indonesia',
    grade: 7,
    topic: 'Laporan Hasil Observasi',
    difficulty: 'medium',
    question: 'Kalimat manakah yang berisi fakta?',
    options: ['Kucing itu hewan paling lucu.', 'Air mendidih pada suhu 100°C pada tekanan normal.', 'Menurutku, hujan hari ini menyebalkan.', 'Pemandangan itu sangat indah.'],
    correctAnswer: 1,
    explanation: 'Kalimat kedua bisa dibuktikan lewat pengamatan atau pengukuran, jadi termasuk fakta.',
    hint: 'Fakta dapat dibuktikan, sedangkan pendapat bergantung pada penilaian seseorang.',
    source: 'local_bank',
  },
  {
    id: 'ind-008',
    subject: 'indonesia',
    grade: 8,
    topic: 'Teks Berita',
    difficulty: 'easy',
    question: 'Unsur berita yang menjawab pertanyaan “siapa yang terlibat?” adalah ...',
    options: ['Apa', 'Siapa', 'Kapan', 'Mengapa'],
    correctAnswer: 1,
    explanation: 'Unsur “siapa” menunjukkan tokoh atau pihak yang terlibat dalam peristiwa.',
    hint: 'Cari unsur 5W1H yang langsung menanyakan pelaku.',
    source: 'local_bank',
  },
  {
    id: 'ind-009',
    subject: 'indonesia',
    grade: 8,
    topic: 'Teks Eksposisi',
    difficulty: 'medium',
    question: 'Bagian teks eksposisi yang berisi pendapat utama penulis disebut ...',
    options: ['Tesis', 'Argumen', 'Penegasan ulang', 'Orientasi tokoh'],
    correctAnswer: 0,
    explanation: 'Tesis adalah pendapat atau sudut pandang utama yang kemudian didukung oleh argumen.',
    hint: 'Bagian ini menjadi posisi awal penulis terhadap topik.',
    source: 'local_bank',
  },
  {
    id: 'ind-010',
    subject: 'indonesia',
    grade: 9,
    topic: 'Teks Diskusi',
    difficulty: 'medium',
    question: 'Teks diskusi biasanya menyajikan ...',
    options: ['Satu pendapat tanpa alasan', 'Argumen yang mendukung dan menentang topik', 'Langkah membuat suatu benda', 'Daftar tokoh cerita'],
    correctAnswer: 1,
    explanation: 'Teks diskusi membandingkan sisi pro dan kontra sebelum membuat simpulan.',
    hint: 'Kata kuncinya adalah melihat sebuah masalah dari dua sisi.',
    source: 'local_bank',
  },
  {
    id: 'ind-011',
    subject: 'indonesia',
    grade: 9,
    topic: 'Kalimat Efektif',
    difficulty: 'easy',
    question: 'Kalimat yang paling efektif adalah ...',
    options: ['Para siswa-siswa sedang belajar.', 'Para siswa sedang belajar.', 'Para siswa sedang belajar-belajar.', 'Siswa para sedang belajar.'],
    correctAnswer: 1,
    explanation: 'Kata “para” sudah menunjukkan jumlah banyak, jadi kata “siswa” tidak perlu diulang.',
    hint: 'Hindari penanda jamak yang dipakai dua kali.',
    source: 'local_bank',
  },
  {
    id: 'eng-007',
    subject: 'inggris',
    grade: 7,
    topic: 'Greetings and Introduction',
    difficulty: 'easy',
    question: 'A: “How are you?” B: “...”',
    options: ['I’m fine, thank you.', 'My name is Raka.', 'See you tomorrow.', 'Good night yesterday.'],
    correctAnswer: 0,
    explanation: '“How are you?” menanyakan kabar. Jawaban yang cocok adalah “I’m fine, thank you.”',
    hint: 'Pilih jawaban yang menunjukkan keadaan atau kabar.',
    source: 'local_bank',
  },
  {
    id: 'eng-008',
    subject: 'inggris',
    grade: 7,
    topic: 'Descriptive Text',
    difficulty: 'easy',
    question: 'The school library is ... It has many tables and wide windows.',
    options: ['spacious', 'spaciously', 'spaciousness', 'space'],
    correctAnswer: 0,
    explanation: 'Setelah “is” kita membutuhkan adjective atau kata sifat. “Spacious” berarti luas.',
    hint: 'Cari kata sifat yang menerangkan keadaan library.',
    source: 'local_bank',
  },
  {
    id: 'eng-009',
    subject: 'inggris',
    grade: 8,
    topic: 'Modal Auxiliaries',
    difficulty: 'easy',
    question: 'You ... wear a helmet when riding a motorcycle.',
    options: ['must', 'might to', 'can to', 'are'],
    correctAnswer: 0,
    explanation: '“Must” dipakai untuk menyatakan kewajiban. Setelah modal, gunakan kata kerja dasar: “must wear”.',
    hint: 'Kalimat ini berisi aturan yang wajib dilakukan.',
    source: 'local_bank',
  },
  {
    id: 'eng-010',
    subject: 'inggris',
    grade: 8,
    topic: 'Invitation and Announcement',
    difficulty: 'easy',
    question: 'A: “Would you like to join our study group?” B: “...”',
    options: ['That sounds great!', 'I am a student.', 'It was yesterday.', 'The group is blue.'],
    correctAnswer: 0,
    explanation: 'Pertanyaan itu adalah undangan. “That sounds great!” merupakan respons menerima undangan.',
    hint: 'Pilih respons yang menunjukkan seseorang senang diajak.',
    source: 'local_bank',
  },
  {
    id: 'eng-011',
    subject: 'inggris',
    grade: 9,
    topic: 'Report Text',
    difficulty: 'easy',
    question: 'Which sentence states a general fact about whales?',
    options: ['Whales are mammals.', 'Whales visited my beach yesterday.', 'I saw one whale last Sunday.', 'The whale was happy in the story.'],
    correctAnswer: 0,
    explanation: 'Report text membahas fakta umum. “Whales are mammals” menyatakan fakta tentang paus secara umum.',
    hint: 'Pilih kalimat yang berlaku untuk paus secara umum, bukan pengalaman tertentu.',
    source: 'local_bank',
  },
  {
    id: 'eng-012',
    subject: 'inggris',
    grade: 9,
    topic: 'Opinion and Persuasion',
    difficulty: 'medium',
    question: 'Which sentence expresses an opinion?',
    options: ['I think reading is a useful habit.', 'The library opens at seven.', 'Water freezes at zero degrees Celsius.', 'Rina has two notebooks.'],
    correctAnswer: 0,
    explanation: '“I think” menandai pendapat pribadi, bukan fakta yang bisa berlaku untuk semua orang.',
    hint: 'Cari kalimat yang memakai penanda pendapat.',
    source: 'local_bank',
  },

  {
    id: 'mat-014',
    subject: 'matematika',
    grade: 8,
    topic: 'Lingkaran',
    difficulty: 'medium',
    question: 'Sebuah lingkaran punya jari-jari 7 cm. Berapa luasnya jika π = 22 ÷ 7?',
    options: ['44 cm²', '154 cm²', '308 cm²', '616 cm²'],
    correctAnswer: 1,
    explanation: 'Luas = π × r² = 22 ÷ 7 × 7² = 22 × 7 = 154 cm².',
    hint: 'Gunakan luas = π × jari-jari².',
    source: 'local_bank',
  },
  {
    id: 'mat-015',
    subject: 'matematika',
    grade: 9,
    topic: 'Kesebangunan dan Kekongruenan',
    difficulty: 'medium',
    question: 'Dua segitiga sebangun memiliki sisi bersesuaian 4 cm dan 6 cm. Jika sisi kecil lainnya 8 cm, berapa sisi pasangannya pada segitiga besar?',
    options: ['10 cm', '12 cm', '14 cm', '16 cm'],
    correctAnswer: 1,
    explanation: 'Skala dari kecil ke besar = 6 ÷ 4 = 1,5. Jadi sisi pasangannya = 8 × 1,5 = 12 cm.',
    hint: 'Cari faktor skala dari 4 cm menjadi 6 cm, lalu pakai untuk sisi 8 cm.',
    source: 'local_bank',
  },
  {
    id: 'ipa-013',
    subject: 'ipa',
    grade: 7,
    topic: 'Zat dan Perubahannya',
    difficulty: 'easy',
    question: 'Es batu yang mencair menjadi air mengalami perubahan ...',
    options: ['Kimia', 'Fisika', 'Biologi', 'Nuklir'],
    correctAnswer: 1,
    explanation: 'Mencair hanya mengubah wujud dari padat menjadi cair. Zatnya tetap air, jadi ini perubahan fisika.',
    hint: 'Tanyakan: apakah terbentuk zat baru atau hanya berubah wujud?',
    source: 'local_bank',
  },
  {
    id: 'ipa-014',
    subject: 'ipa',
    grade: 7,
    topic: 'Ekosistem dan Keanekaragaman',
    difficulty: 'easy',
    question: 'Dalam rantai makanan rumput → belalang → katak → ular, yang berperan sebagai konsumen pertama adalah ...',
    options: ['Rumput', 'Belalang', 'Katak', 'Ular'],
    correctAnswer: 1,
    explanation: 'Rumput adalah produsen. Belalang memakan rumput, jadi belalang menjadi konsumen pertama.',
    hint: 'Konsumen pertama memakan produsen.',
    source: 'local_bank',
  },
  {
    id: 'ipa-015',
    subject: 'ipa',
    grade: 8,
    topic: 'Struktur dan Jaringan Tumbuhan',
    difficulty: 'easy',
    question: 'Jaringan tumbuhan yang mengangkut air dan mineral dari akar ke daun adalah ...',
    options: ['Floem', 'Xilem', 'Epidermis', 'Kambium'],
    correctAnswer: 1,
    explanation: 'Xilem membawa air dan mineral dari akar ke bagian atas tumbuhan. Floem mengangkut hasil fotosintesis.',
    hint: 'Ingat: xilem membawa air naik dari akar.',
    source: 'local_bank',
  },
  {
    id: 'ipa-016',
    subject: 'ipa',
    grade: 9,
    topic: 'Kimia dan Lingkungan',
    difficulty: 'medium',
    question: 'Cara yang paling tepat untuk mengurangi sampah plastik sekali pakai adalah ...',
    options: ['Membakarnya di ruang tertutup', 'Memakai ulang dan mendaur ulang', 'Membuangnya ke sungai', 'Menimbunnya di halaman'],
    correctAnswer: 1,
    explanation: 'Memakai ulang dan mendaur ulang mengurangi jumlah plastik yang masuk ke lingkungan tanpa menghasilkan asap berbahaya.',
    hint: 'Pilih tindakan yang mengurangi sampah dari sumbernya.',
    source: 'local_bank',
  },
  {
    id: 'ips-012',
    subject: 'ips',
    grade: 7,
    topic: 'Pranata Sosial dan Lingkungan',
    difficulty: 'easy',
    question: 'Sekolah, keluarga, dan lembaga agama termasuk contoh ...',
    options: ['Pranata sosial', 'Sumber daya alam', 'Bentuk muka bumi', 'Kegiatan ekspor'],
    correctAnswer: 0,
    explanation: 'Pranata sosial adalah sistem aturan atau lembaga yang membantu memenuhi kebutuhan dan mengatur kehidupan masyarakat.',
    hint: 'Pikirkan lembaga yang punya aturan dan peran dalam masyarakat.',
    source: 'local_bank',
  },
  {
    id: 'ips-013',
    subject: 'ips',
    grade: 8,
    topic: 'Kegiatan Ekonomi',
    difficulty: 'easy',
    question: 'Orang yang memakai barang atau jasa untuk memenuhi kebutuhan disebut ...',
    options: ['Produsen', 'Distributor', 'Konsumen', 'Investor'],
    correctAnswer: 2,
    explanation: 'Konsumen memakai atau mengonsumsi barang dan jasa. Produsen membuatnya, sedangkan distributor menyalurkannya.',
    hint: 'Cari pelaku ekonomi yang menggunakan barang atau jasa.',
    source: 'local_bank',
  },
  {
    id: 'ips-014',
    subject: 'ips',
    grade: 9,
    topic: 'Peristiwa Kemerdekaan Indonesia',
    difficulty: 'easy',
    question: 'Proklamasi Kemerdekaan Indonesia dibacakan pada tanggal ...',
    options: ['17 Agustus 1945', '10 November 1945', '28 Oktober 1928', '20 Mei 1908'],
    correctAnswer: 0,
    explanation: 'Proklamasi Kemerdekaan Indonesia dibacakan pada 17 Agustus 1945 oleh Soekarno didampingi Mohammad Hatta.',
    hint: 'Tanggal ini diperingati setiap tahun sebagai Hari Kemerdekaan.',
    source: 'local_bank',
  },
  {
    id: 'ips-015',
    subject: 'ips',
    grade: 9,
    topic: 'Kerja Sama Internasional',
    difficulty: 'medium',
    question: 'Kerja sama beberapa negara dalam satu kawasan, seperti Asia Tenggara, disebut kerja sama ...',
    options: ['Bilateral', 'Regional', 'Individual', 'Rumah tangga'],
    correctAnswer: 1,
    explanation: 'Kerja sama regional melibatkan negara-negara dalam kawasan tertentu. ASEAN adalah salah satu contohnya.',
    hint: 'Regional berarti berkaitan dengan suatu wilayah atau kawasan.',
    source: 'local_bank',
  },
  {
    id: 'ips-016',
    subject: 'ips',
    grade: 9,
    topic: 'Kependudukan dan Pembangunan',
    difficulty: 'easy',
    question: 'Perbandingan jumlah penduduk dengan luas wilayah disebut ...',
    options: ['Kepadatan penduduk', 'Mobilitas sosial', 'Komposisi ekonomi', 'Migrasi internasional'],
    correctAnswer: 0,
    explanation: 'Kepadatan penduduk menunjukkan banyaknya penduduk dalam setiap satuan luas wilayah.',
    hint: 'Istilah ini menggabungkan jumlah orang dan luas tempat tinggalnya.',
    source: 'local_bank',
  },
  {
    id: 'ind-012',
    subject: 'indonesia',
    grade: 7,
    topic: 'Cerita Fantasi',
    difficulty: 'easy',
    question: 'Ciri yang paling menonjol dari cerita fantasi adalah ...',
    options: ['Berisi langkah kerja nyata', 'Menghadirkan kejadian atau dunia yang imajinatif', 'Selalu memuat data angka', 'Hanya menceritakan berita terbaru'],
    correctAnswer: 1,
    explanation: 'Cerita fantasi memakai imajinasi, misalnya benda bisa berbicara atau tokoh masuk ke dunia ajaib.',
    hint: 'Cari pilihan yang berhubungan dengan khayalan atau keajaiban.',
    source: 'local_bank',
  },
  {
    id: 'ind-013',
    subject: 'indonesia',
    grade: 8,
    topic: 'Iklan, Slogan, dan Poster',
    difficulty: 'easy',
    question: 'Kalimat “Hemat listrik, selamatkan bumi!” paling tepat disebut ...',
    options: ['Slogan', 'Berita', 'Resensi', 'Laporan percobaan'],
    correctAnswer: 0,
    explanation: 'Slogan adalah kalimat singkat, menarik, dan mudah diingat untuk menyampaikan pesan atau ajakan.',
    hint: 'Kalimatnya singkat dan mengajak orang melakukan sesuatu.',
    source: 'local_bank',
  },
  {
    id: 'ind-014',
    subject: 'indonesia',
    grade: 8,
    topic: 'Teks Persuasi',
    difficulty: 'medium',
    question: 'Tujuan utama teks persuasi adalah ...',
    options: ['Mengajak pembaca mengikuti gagasan penulis', 'Menceritakan tokoh khayalan', 'Menjelaskan langkah percobaan saja', 'Menyusun daftar pustaka'],
    correctAnswer: 0,
    explanation: 'Teks persuasi berusaha meyakinkan dan mengajak pembaca melalui alasan, data, atau kata-kata yang menyentuh.',
    hint: 'Persuasi berkaitan dengan ajakan dan usaha meyakinkan.',
    source: 'local_bank',
  },
  {
    id: 'ind-015',
    subject: 'indonesia',
    grade: 9,
    topic: 'Pidato Persuasif',
    difficulty: 'medium',
    question: 'Kalimat yang cocok sebagai ajakan dalam pidato tentang kebersihan adalah ...',
    options: ['Mari kita buang sampah pada tempatnya.', 'Sampah itu ada di dekat pintu.', 'Kemarin hujan turun deras.', 'Tempat sampah berwarna hijau.'],
    correctAnswer: 0,
    explanation: 'Kata “mari” menunjukkan ajakan. Kalimat ini mendorong pendengar melakukan tindakan yang jelas.',
    hint: 'Cari kata yang mengajak pendengar bertindak bersama.',
    source: 'local_bank',
  },
  {
    id: 'ind-016',
    subject: 'indonesia',
    grade: 9,
    topic: 'Resensi dan Kritik Sastra',
    difficulty: 'medium',
    question: 'Resensi buku biasanya berisi ...',
    options: ['Penilaian terhadap kelebihan dan kekurangan buku', 'Daftar semua kata dalam buku', 'Jadwal pelajaran penulis', 'Langkah membuat buku'],
    correctAnswer: 0,
    explanation: 'Resensi memperkenalkan isi buku lalu menilai kelebihan, kekurangan, dan kelayakannya untuk dibaca.',
    hint: 'Resensi bukan hanya ringkasan, tetapi juga penilaian.',
    source: 'local_bank',
  },
  {
    id: 'eng-013',
    subject: 'inggris',
    grade: 7,
    topic: 'Procedure Text',
    difficulty: 'easy',
    question: 'Which word is commonly used to start a step in a procedure text?',
    options: ['First', 'Yesterday', 'Beautiful', 'Because'],
    correctAnswer: 0,
    explanation: '“First” menunjukkan langkah pertama dalam sebuah procedure text.',
    hint: 'Pilih kata yang menunjukkan urutan langkah.',
    source: 'local_bank',
  },
  {
    id: 'eng-014',
    subject: 'inggris',
    grade: 8,
    topic: 'Recount Text',
    difficulty: 'easy',
    question: 'A recount text mainly tells about ...',
    options: ['A past experience', 'A future plan only', 'A general definition', 'A list of ingredients'],
    correctAnswer: 0,
    explanation: 'Recount text menceritakan kembali pengalaman atau kejadian yang sudah berlangsung.',
    hint: 'Ingat, recount berkaitan dengan cerita atau pengalaman masa lalu.',
    source: 'local_bank',
  },
  {
    id: 'eng-015',
    subject: 'inggris',
    grade: 8,
    topic: 'Invitation and Announcement',
    difficulty: 'easy',
    question: 'Which sentence is a polite invitation?',
    options: ['Would you like to come to my party?', 'Close the door now.', 'I went to the party yesterday.', 'The party is colorful.'],
    correctAnswer: 0,
    explanation: '“Would you like to ...?” adalah ungkapan sopan untuk mengundang seseorang.',
    hint: 'Cari kalimat yang menawarkan seseorang untuk datang.',
    source: 'local_bank',
  },
  {
    id: 'eng-016',
    subject: 'inggris',
    grade: 9,
    topic: 'Narrative and Folklore',
    difficulty: 'easy',
    question: 'The main purpose of a narrative text is to ...',
    options: ['Entertain the reader with a story', 'Give a phone number', 'Explain a scientific formula', 'List school rules'],
    correctAnswer: 0,
    explanation: 'Narrative text bertujuan menghibur pembaca lewat cerita, biasanya dengan tokoh, konflik, dan penyelesaian.',
    hint: 'Narrative berarti teks berbentuk cerita.',
    source: 'local_bank',
  },

  ...ADDITIONAL_QUESTION_BANK,
];

export function getLocalQuestions(subject: Subject, grade?: GradeLevel): Question[] {
  return QUESTION_BANK.filter((q) => {
    if (q.subject !== subject) return false;
    if (grade && q.grade !== grade) return false;
    return true;
  });
}

function isTopicMatch(questionTopic: string, requestedTopic: string): boolean {
  const questionValue = questionTopic.toLowerCase();
  const requestedValue = requestedTopic.toLowerCase();
  if (
    questionValue === requestedValue ||
    questionValue.includes(requestedValue) ||
    requestedValue.includes(questionValue)
  ) {
    return true;
  }

  // Beberapa nama subbab di bank lama lebih spesifik daripada label menu baru
  // (misalnya “Sejarah Kerajaan ...” dan “Kerajaan Nusantara”). Satu kata inti
  // yang bermakna sudah cukup untuk memilih fallback yang masih satu bahasan.
  const ignoredWords = new Set(['dan', 'atau', 'teks', 'sistem', 'serta', 'dengan', 'untuk']);
  const words = (value: string) =>
    value
      .split(/[^a-z0-9]+/)
      .filter((word) => word.length >= 5 && !ignoredWords.has(word));
  const questionWords = words(questionValue);
  const requestedWords = new Set(words(requestedValue));
  return questionWords.some((word) => requestedWords.has(word));
}

/**
 * Ambil soal lokal sesuai mapel, kelas, dan subbab bila tersedia.
 * Saat semua soal di pool sudah dipakai, pool yang lebih luas dipakai agar ronde
 * tetap berjalan tanpa mengulang soal terus-menerus selama masih ada pilihan lain.
 */
export function getRandomLocalQuestion(
  subject: Subject,
  grade?: GradeLevel,
  excludeIds: string[] = [],
  requestedTopic?: string
): Question {
  const gradeQuestions = getLocalQuestions(subject, grade);
  const topicQuestions = requestedTopic
    ? gradeQuestions.filter((question) => isTopicMatch(question.topic, requestedTopic))
    : gradeQuestions;
  const preferredPool = topicQuestions.length > 0 ? topicQuestions : gradeQuestions;

  let available = preferredPool.filter((question) => !excludeIds.includes(question.id));
  if (available.length === 0) {
    available = gradeQuestions.filter((question) => !excludeIds.includes(question.id));
  }
  if (available.length === 0) {
    // Semua soal pada kelas ini sudah dipakai; mulai siklus baru dari mapel yang sama.
    available = getLocalQuestions(subject).filter((question) => !excludeIds.includes(question.id));
  }
  if (available.length === 0) {
    // Fallback terakhir agar mode offline tetap bisa dimainkan.
    available = QUESTION_BANK.filter((question) => question.subject === subject);
  }
  if (available.length === 0) {
    available = QUESTION_BANK;
  }

  const index = Math.floor(Math.random() * available.length);
  return formatQuestion(available[index]);
}
